### ISSUE TITLE
Full-screen forced in latest xmonad version

### ISSUE THREAD

**Issue by hicolour** [altercation/dotfiles-tilingwm#4]
Hi @altercation, I'm having issue while using your xmonad config with latest xmonad. Mainly new window is forced to run in full screen mode, what's more layout cannot be changed. I was trying to identify the root cause by looking on xmonad changelog but I have realy hard time doing that. Maybe you could give me some tips. Many thanks in advance.

**Comment by petitetit** [comment]
Having the same issue still, what have you done to fix this?
